version: "3"
services:
  api:
    build: .
    # command: "yarn dev --legacy-watch" # enable hot reload
    ports:
      - "3001:3001"
    container_name: api
    restart: always
    env_file:
      - docker.api.env
    volumes:
      # - ./:/usr/src/app # enable hot reload
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb
    restart: always
    env_file:
      - docker.db.env
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data/:/data/db

volumes:
  mongo-data:
